loadNet:
  task: classification
  model_type: resnet18
  backbone: null
  mode: single
  # mode: single/full

version: 1

infer:
  infer_type: trt
  input_shape: null

build_engine:
  engine_type: trt
  
####################################
torch:
  model_path: null
  load_pretrained: true
  pretrained:
    model_path: null
  verbose: false
  return_path: null
  
build_torch:
  model_path: null
  verbose: false

####################################
onnx:
  model_path: null
  load_pretrained: true
  verbose: false
  return_path: true
  pretrained:
    model_path: null
    input_shape: null
    batch_size: -1
    opset_version: 11
  # below for build_onnx
  torch_model_path: null
  batch_size: null
  input_shape: null
  opset_version: 11


Is_Pretrained_Onnx_Matched:
  input_shape: null
  batch_size: -1
  opset_version: 11


build_onnx:
  torch_model_path: null
  onnx_model_path: ???
  batch_size: ???
  input_shape: ???
  opset_version: 11
  verbose: false

####################################
trt:
  model_path: null
  load_pretrained: true
  return_path: null
  verbose: false
  pretrained:
    fp16:
      model_path: null
      batch_size: -1
      input_shape: null
      precision: fp16
    int8:
      model_path: null
      batch_size: -1
      input_shape: null
      precision: int8
    fp32:
      model_path: null
      batch_size: -1
      input_shape: null
      precision: fp32
    
  # below for build_trt_engine
  onnx_model_path: null
  trt_model_path: null
  input_shape: null
  batch_size: null
  precision: int8
  max_workspace_size: 1<<31
  calibrate_cache: null
  calibrator: null
  max_batch_size: 32
  calibrate_dir: null
  source_dir: null

Is_Pretrained_Trt_Matched:
  input_shape: null
  batch_size: -1
  precision: int8

build_trt_engine:
  onnx_model_path: null
  trt_model_path: null
  input_shape: null
  batch_size: null
  precision: int8
  max_workspace_size: 1<<31
  max_batch_size: 32
  explicit_batch: true
  # below for int8 calibrator
  calibrator: null
  calibrate_cache: null
  calibrate_dir: null
  source_dir: null


  
####################################

preprocess:
  dst_dir: ???
  source_dir: null
  source_file: null
  force_preprocess: false
  verbose: false

preprocess_one:
  source_name: null

  
postprocess:
  batch_size: -1
  